export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_FAIL = "ACTIVATION_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const USER_LOAD_FAIL = "USER_LOAD_FAIL";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";
export const LOGOUT = "LOGOUT";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";
export const USER_LOADED = "USER_LOADED";
export const USER_FINALIZED = "USER_FINALIZED";
export const TEAMS_LOADED = "TEAMS_LOADED";

// gameweek
export const GW_TEAM_LOADED_SUCCESS = "GW_TEAM_LOADED_SUCCESS";
export const PLAYER_ADDED = "PLAYER_ADDED";
export const PLAYING_TEAM_CHANGED = "PLAYING_TEAM_CHANGED";
export const SUBS_CHANGED = "SUBS_CHANGED";
export const CAPTAIN_CHANGED = "CAPTAIN_CHANGED";
export const VICE_CAPTAIN_CHANGED = "VICE_CAPTAIN_CHANGED";
export const PLAYER_REMOVED = "PLAYER_REMOVED";
export const RESET_TEAM = "RESET_TEAM";
export const CONFIRM_TRANSFERS = "CONFIRM_TRANSFERS";
export const GW_BUDGET_UPDATED = "GW_BUDGET_UPDATED";
export const RESET_PLAYING_TEAM = "RESET_PLAYING_TEAM";
export const RESET_SUBS = "RESET_SUBS";
export const RESET_CAPTAIN = "RESET_CAPTAIN";
export const RESET_VICE_CAPTAIN = "RESET_VICE_CAPTAIN";
export const CONFIRM_PLAYING_TEAM = "CONFIRM_PLAYING_TEAM";

// errors
export const GET_ERRORS = "GET_ERRORS";
export const SWITCH_ERROR_OFF = "SWITCH_ERROR_OFF";
