INSERT INTO FPL.GW_TEAMS (USER_ID, GW, GW_POINTS, TRANSFER_REM, CAPTAIN, VICE_CAPTAIN) VALUES (1, 13, 0, 0, 22, 474);
INSERT INTO FPL.GW_TEAMS (USER_ID, GW, GW_POINTS, TRANSFER_REM, CAPTAIN, VICE_CAPTAIN) VALUES (3, 13, 0, 0, 438, 538);
INSERT INTO FPL.GW_TEAMS (USER_ID, GW, GW_POINTS, TRANSFER_REM, CAPTAIN, VICE_CAPTAIN) VALUES (1, 12, 14, 0, 22, 474);
INSERT INTO FPL.GW_TEAMS (USER_ID, GW, GW_POINTS, TRANSFER_REM, CAPTAIN, VICE_CAPTAIN) VALUES (1, 11, 22, 0, 22, 474);
INSERT INTO FPL.GW_TEAMS (USER_ID, GW, GW_POINTS, TRANSFER_REM, CAPTAIN, VICE_CAPTAIN) VALUES (3, 12, 16, 0, 438, 538);
